version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/alita-dform

    steps:
      - checkout
      - attach_workspace:
          at: ~/alita-dform
      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test:coverage --forceExit --detectOpenHandles --runInBand
          no_output_timeout: 300m
      - run:
          name: Generate coverage
          command: bash <(curl -s https://codecov.io/bash)
