name: Node CI

on:
  push:
    paths-ignore:
      - '.github/**/*.md'
      - 'examples/**'
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12.x, 14.x]
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.yarnpkg.com'
      - name: install
        run: yarn
      - run: yarn test --detectOpenHandles --maxWorkers=1 --forceExit
        env:
          CI: true
          HEADLESS: false
          PROGRESS: none
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096
