name: Node CI

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    paths-ignore:
      - 'examples/**'
      - 'docs/**'
      - '**/*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14.x, 16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org/'
      - name: install
        run: yarn
      - run: yarn build
      - run: yarn test --detectOpenHandles --maxWorkers=1 --forceExit
        env:
          CI: true
          NODE_ENV: test
